### ISSUE TITLE
Pass active language in context

### ISSUE THREAD

**Issue by treylon** [eversport/intl-codegen#21]
It would help a lot to expose the current language in the context, especially in SSR rendered apps.

**Comment by Swatinem** [comment]
`Intl.locale` already exists

**Comment by Swatinem** [comment]
BTW, I am planning to introduce also a breaking change for this in v2.
Currently all the number/date formatting is based on the language you author the translations in.
So currently `Intl.locale` is whatever you generate with the codegen.
In the future, I would like to make `locale` whatever the user requests.
So if the `navigator.language` is `de-at`, you would get currency formatting for austrian german that is different for swiss german, even if you only have a single translation bundle for the german language.
