### ISSUE TITLE
Do not throw on invalid language tags

### ISSUE THREAD

**Issue by Swatinem** [eversport/intl-codegen#39]
When using `loadLanguage(["*"])`, I get the following error:

```
    RangeError: Invalid language tag: *
        at new NumberFormat (native)
```

We should try/catch that if possible and make sure that `loadLanguage` never throws.

Discovered using headless puppeteer, as that does not send any `Accept-Language` header…
https://github.com/GoogleChrome/puppeteer/issues/665#issuecomment-356634721

**Comment by treylon** [comment]
In which applications do you find this behavior?
