### ISSUE TITLE
Declarative / lazy API

### ISSUE THREAD

**Issue by Swatinem** [eversport/intl-codegen#44]
Currently `intl-codegen` creates two different APIs:

* a direct imperative API based on function calls
* a declarative / lazy API specifically for react

It would be nice to combine the best of these two worlds, which should actually be quite straight-forward.

The react types already generate a big union type which has all the translations as data:
```ts
type LocalizedType =
  | {
    id: "foo",
  }
  | {
    id: "bar",
    params: { param: string },
  }
```

We can expose this generic data-type more directly, and expose a function which can consume it in a type-safe way.

I see two ways to do this without a backwards incompatible break:

1. make `IntlObject` a function. So you can do:
```ts
const intl = await loadLanguage(locale);
return intl({ id: "bar", params: { param: "foobar" } });
```
2. attach such a function to the `context`, maybe via `intl.context.translate({ id: "bar", params: { param: "foobar" } })`

I definitely like the first approach better.

One important thing would be to bikeshed the exported name of this… Suggestions welcome…

BTW, a bit related to this, but I have been brainstorming for quite some time how to best do such a stricty-typed codegen project for Rust, and the idea I had also came very close to this:

```rust
enum Translation
  Foo,
  Bar { param: String },
}

trait Intl {
  pub fn translate(translation: &Translation) -> String;
}
```

or something similar to this…

That way, you can completely split up the **what** you want to translate, and **how** to actually translate it. With plain data as the interface.

**Comment by y4nnick** [comment]
Nice one!!!

 - I would prefer `TranslationKey` instead of `LocalizedType`.
 - Since `intl.translate` is not possible because it is possible that there is a translation called `translate`, i would prefer the first solution `intl(translationKey: TranslationKey)`.

**Comment by Swatinem** [comment]
@y4nnick @rfbotto please take a look at the test fixtures here to get a feel for the new API, and give some feedback

https://github.com/eversport/intl-codegen/commit/67bf74463cf722707d63e3aa3c53165abfbd8468#diff-c715796798054d3b612ccd1eae6b2339

**Comment by y4nnick** [comment]
Very nice! Thanks arpad!

Nice code and tests as always :).
